#!/bin/bash
#===========================================================================
#
# This file is licensed under the terms of the GNU General Public
# License version 2. This program is licensed "as is" without any
# warranty of any kind, whether express or implied.
#
# This file is a part of the Rebuild Armbian
# https://github.com/ophub/amlogic-s9xxx-armbian
#
# Description: Change the source of the system
# Copyright (C) 2021- https://github.com/ophub/amlogic-s9xxx-armbian
#
# Command: armbian-apt
#
#============================= Functions list #=============================
#
# error_msg           : Output error message
# check_release       : Check the system release
# change_source_list  : Change the source of the system
# select_mirror_site  : Select the mirror site
#
#========================= Set default parameters ==========================
#
# Set the default source of the system
armbian_source_file=""

# Set font color
STEPS="[\033[95m STEPS \033[0m]"
INFO="[\033[94m INFO \033[0m]"
SUCCESS="[\033[92m SUCCESS \033[0m]"
OPTIONS="[\033[93m OPTIONS \033[0m]"
ERROR="[\033[91m ERROR \033[0m]"
#
#===========================================================================

# Encountered a serious error, abort the script execution
error_msg() {
    echo -e "${ERROR} ${1}"
    exit 1
}

# Check the system release
check_release() {
    if [[ -f "/etc/os-release" ]]; then
        source "/etc/os-release"
        [[ -z "${VERSION_CODENAME}" ]] && error_msg "The system VERSION_CODENAME is not detected!"

        case "${VERSION_CODENAME}" in
        trixie)
            armbian_source_file="/etc/apt/sources.list.d/debian.sources"
            ;;
        noble | resolute)
            armbian_source_file="/etc/apt/sources.list.d/ubuntu.sources"
            ;;
        esac
        [[ -z "${armbian_source_file}" ]] && error_msg "The system release is not detected: [ ${VERSION_CODENAME} ]"
    else
        error_msg "The system release file is not detected!"
    fi
}

# Change the source of the system
change_source_list() {
    echo -e "${STEPS} Start to change the source of the system: [ ${MIRROR_URL} ]"
    echo -e "${INFO} The system release is: [ ${VERSION_CODENAME} ]"

    case "${VERSION_CODENAME}" in
    trixie)
        cat >"${armbian_source_file}" <<EOF
        Types: deb
        URIs: ${DEBIAN_MIRROR}
        Suites: trixie trixie-updates trixie-backports
        Components: main contrib non-free non-free-firmware
        Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

EOF
        cat >>"${armbian_source_file}" <<EOF
        Types: deb
        URIs: ${DEBIAN_SECURITY}/
        Suites: trixie-security
        Components: main contrib non-free non-free-firmware
        Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

EOF
        ;;

    noble | resolute)
        cat >"${armbian_source_file}" <<EOF
        Types: deb
        URIs: ${UBUNTU_MIRROR}/
        Suites: ${VERSION_CODENAME} ${VERSION_CODENAME}-security ${VERSION_CODENAME}-updates ${VERSION_CODENAME}-backports
        Components: main restricted universe multiverse
        Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

EOF
        ;;

    *)
        error_msg "The system release is not detected: [ ${VERSION_CODENAME} ]"
        ;;

    esac

    # Remove the space at the beginning of each line
    sed -i 's|^[ \t]*||' "${armbian_source_file}"
    echo -e "${SUCCESS} Change the source of the system successfully."
}

# Select the mirror site
select_mirror_site() {
    source_id="${1}"
    echo -e "${INFO} Your selected source ID is: [ ${source_id} ]"
    DEBIAN_MIRROR=""
    DEBIAN_SECURITY=""
    UBUNTU_MIRROR=""

    case "${source_id}" in
    0)
        # Restore the default source
        MIRROR_URL="default"
        case "${VERSION_CODENAME}" in
        trixie)
            DEBIAN_MIRROR="http://deb.debian.org/debian"
            DEBIAN_SECURITY="http://security.debian.org"
            ;;
        noble | resolute)
            UBUNTU_MIRROR="http://ports.ubuntu.com/ubuntu-ports"
            ;;
        esac
        change_source_list
        exit 0
        ;;
    1) MIRROR_URL="mirrors.tuna.tsinghua.edu.cn" ;;
    2) MIRROR_URL="mirrors.bfsu.edu.cn" ;;
    3) MIRROR_URL="mirrors.aliyun.com" ;;
    4) MIRROR_URL="mirrors.huaweicloud.com" ;;
    5) MIRROR_URL="mirror.twds.com.tw" ;;
    6) MIRROR_URL="mirror.yandex.ru" ;;
    7) MIRROR_URL="ftp.kaist.ac.kr" ;;
    8) MIRROR_URL="ftp.lanet.kr" ;;
    9) MIRROR_URL="mirror.sg.gs" ;;
    10) MIRROR_URL="mirror.aarnet.edu.au" ;;
    11) MIRROR_URL="mirrors.ocf.berkeley.edu" ;;
    12) MIRROR_URL="files.openstack.org/mirror" ;;
    13)
        MIRROR_URL="steadfastnet.com,leaseweb.net"
        DEBIAN_MIRROR="https://mirror.steadfastnet.com/debian"
        DEBIAN_SECURITY="https://mirror.steadfastnet.com/debian-security"
        UBUNTU_MIRROR="https://mirror.us.leaseweb.net/ubuntu-ports"
        ;;
    14) MIRROR_URL="mirror.csclub.uwaterloo.ca" ;;
    15) MIRROR_URL="mirror.servercodes.com" ;;
    16) MIRROR_URL="ftp.openbsd.dk/mirrors" ;;
    17) MIRROR_URL="mirrors.dotsrc.org" ;;
    18) MIRROR_URL="mirror.dogado.de" ;;
    19)
        MIRROR_URL="ftp.de.debian.org,ftp.fau.de"
        DEBIAN_MIRROR="http://ftp.de.debian.org/debian"
        DEBIAN_SECURITY="http://ftp.de.debian.org/debian-security"
        UBUNTU_MIRROR="https://ftp.fau.de/ubuntu-ports"
        ;;
    20) MIRROR_URL="mirror.yuki.net.uk" ;;
    *) error_msg "The source ID is not detected." ;;
    esac

    DEBIAN_MIRROR="${DEBIAN_MIRROR:-http://${MIRROR_URL}/debian}"
    DEBIAN_SECURITY="${DEBIAN_SECURITY:-http://${MIRROR_URL}/debian-security}"
    UBUNTU_MIRROR="${UBUNTU_MIRROR:-http://${MIRROR_URL}/ubuntu-ports}"

    # Change the source list
    change_source_list
}

echo -e "${STEPS} Welcome to the Armbian source change script."
# Check the system release
check_release

# Prompt the user to input the source ID
echo -e "${INFO} Please select a [\033[92m ${VERSION_CODENAME} \033[0m] mirror site."
cat <<EOF
  ┌──────┬───────────────────┬─────────────────────────────────┐
  │  ID  │  Country/Region   │  Mirror Site                    │
  ├──────┼───────────────────┼─────────────────────────────────┤
  │   0  │  -                │  Restore default source         │
  │   1  │  China            │  mirrors.tuna.tsinghua.edu.cn   │
  │   2  │  China            │  mirrors.bfsu.edu.cn            │
  │   3  │  China            │  mirrors.aliyun.com             │
  │   4  │  China            │  mirrors.huaweicloud.com        │
  │   5  │  Taiwan, China    │  mirror.twds.com.tw             │
  ├──────┼───────────────────┼─────────────────────────────────┤
  │   6  │  Russia           │  mirror.yandex.ru               │
  │   7  │  South Korea      │  ftp.kaist.ac.kr                │
  │   8  │  South Korea      │  ftp.lanet.kr                   │
  │   9  │  Singapore        │  mirror.sg.gs                   │
  │  10  │  Australia        │  mirror.aarnet.edu.au           │
  ├──────┼───────────────────┼─────────────────────────────────┤
  │  11  │  United States    │  mirrors.ocf.berkeley.edu       │
  │  12  │  United States    │  files.openstack.org/mirror     │
  │  13  │  United States    │  steadfastnet.com,leaseweb.net  │
  │  14  │  Canada           │  mirror.csclub.uwaterloo.ca     │
  │  15  │  Canada           │  mirror.servercodes.com         │
  ├──────┼───────────────────┼─────────────────────────────────┤
  │  16  │  Denmark          │  ftp.openbsd.dk/mirrors         │
  │  17  │  Denmark          │  mirrors.dotsrc.org             │
  │  18  │  Germany          │  mirror.dogado.de               │
  │  19  │  Germany          │  ftp.de.debian.org,ftp.fau.de   │
  │  20  │  United Kingdom   │  mirror.yuki.net.uk             │
  └──────┴───────────────────┴─────────────────────────────────┘
EOF
echo -ne "${OPTIONS} Please Input ID: "
read -r mwid

case "${mwid}" in
    [0-9]*) select_mirror_site "${mwid}" ;;
         *) error_msg "Input error." && exit 0 ;;
esac
